### ISSUE TITLE
Cannot install inertiajs server while using vuejs 3

### ISSUE THREAD

**Issue by alslimany** [inertiajs/server#3]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @inertiajs/inertia@0.10.1
npm ERR! node_modules/@inertiajs/inertia
npm ERR!   dev @inertiajs/inertia@"^0.10.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @inertiajs/inertia@"^0.11.0" from @inertiajs/server@0.1.0
npm ERR! node_modules/@inertiajs/server
npm ERR!   @inertiajs/server@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/abdullahishtiwy/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abdullahishtiwy/.npm/_logs/2022-01-09T16_48_15_174Z-debug.log

**Comment by secondmanveran** [comment]
Might wanna show some code on how you set it up.

**Comment by alslimany** [comment]
I'm not able to write configuration, this is becasue inertia/server is not able to be installed.
When trying to install inertia/server:
`npm install @inertiajs/server`

Error showed up, and this is the log file:

0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '@inertiajs/server'
0 verbose cli ]
1 info using npm@8.1.2
2 info using node@v12.16.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/abdullahishtiwy/Sites/new-adv/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/abdullahishtiwy/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 timing npm:load:configload Completed in 9ms
20 timing npm:load:setTitle Completed in 14ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 3ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 32ms
27 timing arborist:ctor Completed in 0ms
28 timing idealTree:init Completed in 811ms
29 timing idealTree:userRequests Completed in 7ms
30 silly idealTree buildDeps
31 silly fetch manifest @inertiajs/server@*
32 timing arborist:ctor Completed in 0ms
33 http fetch GET 200 https://registry.npmjs.org/@inertiajs%2fserver 2546ms (cache revalidated)
34 silly fetch manifest @inertiajs/inertia@^0.10.1
35 http fetch GET 200 https://registry.npmjs.org/@inertiajs%2finertia 1728ms (cache revalidated)
36 silly fetch manifest @inertiajs/inertia@^0.11.0
37 timing idealTree Completed in 5105ms
38 timing command:install Completed in 5117ms
39 verbose stack Error: unable to resolve dependency tree
39 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1356:25)
39 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1322:34)
39 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:11)
39 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
39 verbose stack     at async Promise.all (index 1)
39 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:149:5)
39 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:170:5)
40 verbose cwd /Users/abdullahishtiwy/Sites/new-adv
41 verbose Darwin 21.2.0
42 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@inertiajs/server"
43 verbose node v12.16.1
44 verbose npm  v8.1.2
45 error code ERESOLVE
46 error ERESOLVE unable to resolve dependency tree
47 error
48 error While resolving: [1mundefined[22m@[1mundefined[22m
48 error Found: [1m@inertiajs/inertia[22m@[1m0.10.1[22m[2m[22m
48 error [2mnode_modules/@inertiajs/inertia[22m
48 error   [33mdev[39m [1m@inertiajs/inertia[22m@"[1m^0.10.1[22m" from the root project
48 error
48 error Could not resolve dependency:
48 error [35mpeer[39m [1m@inertiajs/inertia[22m@"[1m^0.11.0[22m" from [1m@inertiajs/server[22m@[1m0.1.0[22m[2m[22m
48 error [2mnode_modules/@inertiajs/server[22m
48 error   [1m@inertiajs/server[22m@"[1m*[22m" from the root project
48 error
48 error Fix the upstream dependency conflict, or retry
48 error this command with --force, or --legacy-peer-deps
48 error to accept an incorrect (and potentially broken) dependency resolution.
48 error
48 error See /Users/abdullahishtiwy/.npm/eresolve-report.txt for a full report.
49 verbose exit 1

**Comment by xhava** [comment]
@alslimany  same problem here. did you figure out how to make it works,
some tip, thanks! regards.
![Captura de Pantalla 2022-02-08 a la(s) 23 07 19](https://user-images.githubusercontent.com/4241380/153125694-de8f6498-abf0-45f4-8a37-3504b8b5b49d.png)

**Comment by priyono100** [comment]
same problem


![image](https://user-images.githubusercontent.com/10704801/155856923-505cf1bd-6053-4806-9b7b-bb1c98dec6e5.png)

**Comment by priyono100** [comment]
done with npm install @inertiajs/server --legacy-peer-deps

**Comment by Maninder-cell** [comment]
@cepexs right answer
