### ISSUE TITLE
I can not use the ant-design-vue with ssr

### ISSUE THREAD

**Issue by qq958691165** [inertiajs/server#9]
I refer to https://github.com/inertiajs/server/issues/1 and modify my code, but it has an other error.
```

/home/jack/code/demo/node_modules/@babel/runtime/helpers/esm/defineProperty.js:1
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/jack/code/demo/node_modules/@babel/runtime/helpers/esm/defineProperty.js
require() of ES modules is not supported.
require() of /home/jack/code/demo/node_modules/@babel/runtime/helpers/esm/defineProperty.js from /home/jack/code/demo/node_modules/ant-design-vue/es/pagination/Pagination.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename defineProperty.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/jack/code/demo/node_modules/@babel/runtime/helpers/esm/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13) {
  code: 'ERR_REQUIRE_ESM'
}
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (/home/jack/code/demo/public/js/ssr.js:2876:42)
    at /home/jack/code/demo/node_modules/@inertiajs/inertia-vue3/dist/index.js:1:9383
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

**Comment by qq958691165** [comment]
I have fixed it but not by https://github.com/inertiajs/server/issues/1
## Use typescript
```
mix.ts('resources/js/ssr.ts', 'public/js', {
        compilerOptions: {
            "target": "ES2018",
            "module": "commonjs",
            "moduleResolution": "node",
            "experimentalDecorators": true,
            "emitDecoratorMetadata": true,
            "noImplicitThis": true,
            "noUnusedLocals": false,
            "skipLibCheck": true,
        },
    })
```

## Report "ReferenceError: document is not defined" error
```
mix.vue({
    ...
    useVueStyleLoader: true,
})
```

## Report require xxx.esm.js  ssr.js not support \[ESM .......]
```
mix.webpackConfig({
    ...
    externals: [webpackNodeExternals({
        allowlist: [
            'xxx',
        ]
    })],
})
```
